version: "3.8"
services:
#  Кролики - это не только ценный мех,... (С)
  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
#    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=test
      - RABBITMQ_DEFAULT_PASS=test
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 2147483648
#      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"


# gateway service with endpoints
  fastapi:
    build: ./
    volumes:
      - ./gateway:/app/gateway
#    command: uvicorn main:app --host=0.0.0.0 --port 8000 --reload --log-level=info
    command: python gateway/main.py
    ports:
      - "8888:8888"
    depends_on:
     - rabbitmq

